import Link from "next/link";
import Image from "next/image";
import { CalendarDays, MapPin, ArrowUpRight } from "lucide-react";
import { upcomingEvents } from "../data/events";
import { PageHero } from "../../components/site/page-hero";
import { Reveal } from "../../components/site/reveal";
import { SectionHeading } from "../../components/site/section-heading";

export default function EventsPage() { return <main><PageHero eyebrow="Gather with us" title="Make room for community." description="From Sunday worship to retreats, fellowships, and youth gatherings, there is always a next step to take together." image="/Guessst1.JPG" /><section className="section-pad bg-[var(--cream)]"><div className="container-shell"><Reveal><SectionHeading eyebrow="Coming up at CITAM Kitale" title="Your next good conversation is closer than you think." description="Bring a friend, come with your family, and make yourself at home." /></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{upcomingEvents.map((event, i) => <Reveal key={event.id} delay={i*.08}><article className="editorial-card image-zoom overflow-hidden rounded-[1.5rem]"><div className="relative h-56"><Image src={event.image} alt={event.title} fill className="object-cover" sizes="(max-width: 768px) 100vw, 33vw" /><span className="absolute left-4 top-4 rounded-full bg-[var(--gold)] px-3 py-2 text-xs font-black uppercase tracking-[.12em] text-[var(--navy)]">Event 0{i+1}</span></div><div className="p-6"><h2 className="text-2xl font-bold">{event.title}</h2><div className="mt-5 grid gap-3 text-sm text-[var(--muted-ink)]"><span className="flex gap-3"><CalendarDays size={17} className="text-[var(--red)]" />{event.date} · {event.time}</span><span className="flex gap-3"><MapPin size={17} className="text-[var(--red)]" />{event.location}</span></div><Link href={`/register/${event.slug}`} className="mt-7 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[var(--red)]">Register interest <ArrowUpRight size={15} /></Link></div></article></Reveal>)}</div></div></section><section className="bg-[var(--navy)] py-14 text-white"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow text-[var(--gold)]">Every week</p><h2 className="mt-3 text-3xl font-bold">Sunday worship · 8:00 AM and 10:30 AM</h2><p className="mt-2 text-white/60">Kitale Town, Trans Nzoia County</p></div><Link href="/contact" className="rounded-full bg-[var(--gold)] px-6 py-4 text-xs font-black uppercase tracking-[.14em] text-[var(--navy)]">Ask a question <ArrowUpRight className="ml-2 inline" size={16} /></Link></div></section></main>; }
