"use client";

import { FormEvent, useState } from "react";
import { Mail, MapPin, Phone, ArrowUpRight } from "lucide-react";
import { PageHero } from "../../components/site/page-hero";
import { Reveal } from "../../components/site/reveal";

export default function ContactPage() {
  const [status, setStatus] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("Sending your message…");
    const form = new FormData(event.currentTarget);
    try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); if (!response.ok) throw new Error(); event.currentTarget.reset(); setStatus("Thank you. A member of our team will get back to you soon."); } catch { setStatus("We could not send that just now. Please call or WhatsApp us on +254 712 345 678."); }
  }
  return <main><PageHero eyebrow="Reach out" title="We would love to hear from you." description="Whether you have a question, need prayer, or want to find your place at CITAM Kitale, our team is ready to welcome you." image="/Guest2.jpg" /><section className="section-pad bg-[var(--cream)]"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><div><p className="eyebrow">Come say hello</p><h2 className="display-heading mt-4 text-5xl leading-none sm:text-6xl">A real person<br />is listening.</h2><div className="mt-9 grid gap-5 text-sm text-[var(--muted-ink)]"><p className="flex gap-4"><MapPin className="shrink-0 text-[var(--red)]" />Kitale Town, Trans Nzoia County, Kenya</p><p className="flex gap-4"><Phone className="shrink-0 text-[var(--red)]" />+254 712 345 678</p><p className="flex gap-4"><Mail className="shrink-0 text-[var(--red)]" />info@citamkitale.org</p></div><div className="mt-10 border-t border-[var(--line)] pt-6"><p className="eyebrow">Sunday worship</p><p className="mt-2 font-bold">8:00 AM and 10:30 AM</p><p className="mt-1 text-sm text-[var(--muted-ink)]">Come early for a cup of tea and conversation.</p></div></div></Reveal><Reveal delay={.1}><form onSubmit={submit} className="rounded-[2rem] bg-white p-6 shadow-xl shadow-[var(--navy)]/10 md:p-10"><p className="eyebrow">Prayer, questions, next steps</p><h2 className="mt-3 text-3xl font-bold">Send us a note.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Your name<input name="name" required minLength={2} className="rounded-xl border border-[var(--line)] bg-[var(--cream)] px-4 py-3 font-normal outline-none focus:border-[var(--gold-deep)]" placeholder="e.g. Amina Wanjiku" /></label><label className="grid gap-2 text-sm font-bold">Email address<input name="email" type="email" required className="rounded-xl border border-[var(--line)] bg-[var(--cream)] px-4 py-3 font-normal outline-none focus:border-[var(--gold-deep)]" placeholder="you@example.com" /></label></div><label className="mt-5 grid gap-2 text-sm font-bold">How can we help?<textarea name="message" required minLength={10} rows={6} className="rounded-xl border border-[var(--line)] bg-[var(--cream)] px-4 py-3 font-normal outline-none focus:border-[var(--gold-deep)]" placeholder="Share a prayer request, question, or what brought you here…" /></label><div className="mt-6 flex flex-wrap items-center gap-4"><button className="rounded-full bg-[var(--red)] px-6 py-4 text-xs font-black uppercase tracking-[.14em] text-white" type="submit">Send message <ArrowUpRight className="ml-2 inline" size={15} /></button>{status && <p role="status" className="text-sm text-[var(--muted-ink)]">{status}</p>}</div></form></Reveal></div></section></main>;
}
