import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { ministries } from "../data/ministries";
import { PageHero } from "../../components/site/page-hero";
import { Reveal } from "../../components/site/reveal";
import { SectionHeading } from "../../components/site/section-heading";

export default function MinistriesPage() { return <main><PageHero eyebrow="Find your place" title="There is room for your gifts." description="Ministry is not a programme on the side—it is how we become the hands, feet, welcome, and witness of Jesus in Kitale." image="/youthMinistry.jpg" /><section className="section-pad bg-[var(--cream)]"><div className="container-shell"><Reveal><SectionHeading eyebrow="Our ministries" title="Grow with people who get it." description="Explore a place to serve, learn, ask questions, and build friendships that last beyond Sunday." /></Reveal><div className="mt-12 grid gap-8">{ministries.map((ministry, i) => <Reveal key={ministry.id} delay={i*.08}><article id={ministry.anchor} className="grid gap-7 rounded-[2rem] border border-[var(--line)] bg-white p-5 md:grid-cols-[.8fr_1.2fr] md:items-center md:p-7"><div className="image-zoom relative h-64 overflow-hidden rounded-[1.5rem] md:h-72"><Image src={ministry.image} alt={ministry.title} fill className="object-cover" sizes="(max-width: 768px) 100vw, 40vw" /></div><div className="md:px-5"><p className="eyebrow">Ministry 0{i+1}</p><h2 className="mt-3 text-3xl font-bold">{ministry.title}</h2><p className="mt-4 max-w-xl text-base leading-7 text-[var(--muted-ink)]">{ministry.description} We are building a kind, courageous space where people can meet Jesus and make a meaningful contribution to the church family.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[var(--navy)] px-5 py-3 text-xs font-black uppercase tracking-[.14em] text-white">Get involved <ArrowUpRight size={15} /></Link></div></article></Reveal>)}</div></div></section></main>; }
